TRUNCATE TABLE invoice_info;
TRUNCATE TABLE  subscriber;
/
ALTER TABLE INVOICE
ADD CONSTRAINT fk_subscriber
FOREIGN KEY (subscriber_id)
REFERENCES SUBSCRIBER(subscriber_id);
/
ALTER TABLE TARIFF
ADD CONSTRAINT fk_tariff
FOREIGN KEY (TARIFF_ID)
REFERENCES SUBSCRIBER(TARIFF_ID);
/
ALTER TABLE USAGE_TRACKING
ADD CONSTRAINT fk_usage
FOREIGN KEY (subscriber_id)
REFERENCES SUBSCRIBER(subscriber_id);
/
ALTER TABLE subscriber
ADD (tariff_id NUMBER);
/
ALTER TABLE SUBSCRIBER
ADD(usage_id NUMBER);
/
ALTER TABLE SUBSCRIBER  
MODIFY (USAGE_ID NOT NULL)
/
ALTER TABLE SUBSCRIBER
MODIFY (password VARCHAR2(64));
/