TRUNCATE TABLE invoice_info;
TRUNCATE TABLE  subscriber;
/
ALTER TABLE INVOICE
ADD CONSTRAINT fk_subscriber
FOREIGN KEY (SUB_ID)
REFERENCES SUBSCRIBER(SUB_ID);
/
ALTER TABLE TARIFF
ADD CONSTRAINT fk_tariff
FOREIGN KEY (TARIFF_ID)
REFERENCES SUBSCRIBER(TARIFF_ID);
/
ALTER TABLE USAGE_TRACKING
ADD CONSTRAINT fk_usage
FOREIGN KEY (SUB_ID)
REFERENCES SUBSCRIBER(SUB_ID);
/
ALTER TABLE subscriber
ADD (tariff_id NUMBER);