 CREATE USER CELL2I IDENTIFIED BY cell2iapp; 
 GRANT CONNECT TO CELL2I;
 GRANT CREATE SESSION TO CELL2I;
 GRANT CREATE TABLE TO CELL2I;
 GRANT COMMENT ANY TABLE TO CELL2I;
 GRANT CREATE ANY PROCEDURE TO CELL2I;
 GRANT UNLIMITED TABLESPACE TO CELL2I;
 select * from v$session where username= 'CELL2I';
 DROP USER CELL2I;
 /
 CREATE USER cell2iweb identified by cell2i;
 GRANT CONNECT TO cell2iweb;
/
GRANT CREATE SESSION TO TEST1;
GRANT CREATE ANY PROCEDURE TO TEST1;