//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _180705_i2i_Cell2i.WebServiceReferenceV_2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.cell2iwebservice.com", ConfigurationName="WebServiceReferenceV_2.Cell2iWebServiceImpl")]
    public interface Cell2iWebServiceImpl {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://services.cell2iwebservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedResponse isAuthorized(_180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedResponse> isAuthorizedAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://services.cell2iwebservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoResponse getUserInfo(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoResponse> getUserInfoAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequest request);
        
        // CODEGEN: Generating message contract since element name isConnectedReturn from namespace http://services.cell2iwebservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedResponse isConnected(_180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedResponse> isConnectedAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://services.cell2iwebservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoResponse getTariffInfo(_180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoResponse> getTariffInfoAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://services.cell2iwebservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoResponse getUsageInfo(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoResponse> getUsageInfoAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequest request);
        
        // CODEGEN: Generating message contract since element name isDBConnectedReturn from namespace http://services.cell2iwebservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedResponse isDBConnected(_180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedResponse> isDBConnectedAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://services.cell2iwebservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoResponse getInvoiceInfo(_180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoResponse> getInvoiceInfoAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://services.cell2iwebservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordResponse changeUserPassword(_180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordResponse> changeUserPasswordAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isAuthorizedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isAuthorized", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequestBody Body;
        
        public isAuthorizedRequest() {
        }
        
        public isAuthorizedRequest(_180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class isAuthorizedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public isAuthorizedRequestBody() {
        }
        
        public isAuthorizedRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isAuthorizedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isAuthorizedResponse", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedResponseBody Body;
        
        public isAuthorizedResponse() {
        }
        
        public isAuthorizedResponse(_180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class isAuthorizedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isAuthorizedReturn;
        
        public isAuthorizedResponseBody() {
        }
        
        public isAuthorizedResponseBody(bool isAuthorizedReturn) {
            this.isAuthorizedReturn = isAuthorizedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfo", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequestBody Body;
        
        public getUserInfoRequest() {
        }
        
        public getUserInfoRequest(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class getUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public getUserInfoRequestBody() {
        }
        
        public getUserInfoRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfoResponse", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoResponseBody Body;
        
        public getUserInfoResponse() {
        }
        
        public getUserInfoResponse(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class getUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserInfoReturn;
        
        public getUserInfoResponseBody() {
        }
        
        public getUserInfoResponseBody(string getUserInfoReturn) {
            this.getUserInfoReturn = getUserInfoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isConnectedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isConnected", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequestBody Body;
        
        public isConnectedRequest() {
        }
        
        public isConnectedRequest(_180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class isConnectedRequestBody {
        
        public isConnectedRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isConnectedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isConnectedResponse", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedResponseBody Body;
        
        public isConnectedResponse() {
        }
        
        public isConnectedResponse(_180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class isConnectedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isConnectedReturn;
        
        public isConnectedResponseBody() {
        }
        
        public isConnectedResponseBody(string isConnectedReturn) {
            this.isConnectedReturn = isConnectedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTariffInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTariffInfo", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequestBody Body;
        
        public getTariffInfoRequest() {
        }
        
        public getTariffInfoRequest(_180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class getTariffInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public getTariffInfoRequestBody() {
        }
        
        public getTariffInfoRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTariffInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTariffInfoResponse", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoResponseBody Body;
        
        public getTariffInfoResponse() {
        }
        
        public getTariffInfoResponse(_180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class getTariffInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTariffInfoReturn;
        
        public getTariffInfoResponseBody() {
        }
        
        public getTariffInfoResponseBody(string getTariffInfoReturn) {
            this.getTariffInfoReturn = getTariffInfoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsageInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsageInfo", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequestBody Body;
        
        public getUsageInfoRequest() {
        }
        
        public getUsageInfoRequest(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class getUsageInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string infoType;
        
        public getUsageInfoRequestBody() {
        }
        
        public getUsageInfoRequestBody(string userId, string infoType) {
            this.userId = userId;
            this.infoType = infoType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsageInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsageInfoResponse", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoResponseBody Body;
        
        public getUsageInfoResponse() {
        }
        
        public getUsageInfoResponse(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class getUsageInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUsageInfoReturn;
        
        public getUsageInfoResponseBody() {
        }
        
        public getUsageInfoResponseBody(string getUsageInfoReturn) {
            this.getUsageInfoReturn = getUsageInfoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isDBConnectedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isDBConnected", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequestBody Body;
        
        public isDBConnectedRequest() {
        }
        
        public isDBConnectedRequest(_180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class isDBConnectedRequestBody {
        
        public isDBConnectedRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isDBConnectedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isDBConnectedResponse", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedResponseBody Body;
        
        public isDBConnectedResponse() {
        }
        
        public isDBConnectedResponse(_180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class isDBConnectedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isDBConnectedReturn;
        
        public isDBConnectedResponseBody() {
        }
        
        public isDBConnectedResponseBody(string isDBConnectedReturn) {
            this.isDBConnectedReturn = isDBConnectedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInvoiceInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInvoiceInfo", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequestBody Body;
        
        public getInvoiceInfoRequest() {
        }
        
        public getInvoiceInfoRequest(_180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class getInvoiceInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int invoiceCount;
        
        public getInvoiceInfoRequestBody() {
        }
        
        public getInvoiceInfoRequestBody(string userId, int invoiceCount) {
            this.userId = userId;
            this.invoiceCount = invoiceCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInvoiceInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInvoiceInfoResponse", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoResponseBody Body;
        
        public getInvoiceInfoResponse() {
        }
        
        public getInvoiceInfoResponse(_180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class getInvoiceInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInvoiceInfoReturn;
        
        public getInvoiceInfoResponseBody() {
        }
        
        public getInvoiceInfoResponseBody(string getInvoiceInfoReturn) {
            this.getInvoiceInfoReturn = getInvoiceInfoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeUserPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeUserPassword", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequestBody Body;
        
        public changeUserPasswordRequest() {
        }
        
        public changeUserPasswordRequest(_180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class changeUserPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public changeUserPasswordRequestBody() {
        }
        
        public changeUserPasswordRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeUserPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeUserPasswordResponse", Namespace="http://services.cell2iwebservice.com", Order=0)]
        public _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordResponseBody Body;
        
        public changeUserPasswordResponse() {
        }
        
        public changeUserPasswordResponse(_180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.cell2iwebservice.com")]
    public partial class changeUserPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool changeUserPasswordReturn;
        
        public changeUserPasswordResponseBody() {
        }
        
        public changeUserPasswordResponseBody(bool changeUserPasswordReturn) {
            this.changeUserPasswordReturn = changeUserPasswordReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Cell2iWebServiceImplChannel : _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Cell2iWebServiceImplClient : System.ServiceModel.ClientBase<_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl>, _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl {
        
        public Cell2iWebServiceImplClient() {
        }
        
        public Cell2iWebServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Cell2iWebServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Cell2iWebServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Cell2iWebServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedResponse _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.isAuthorized(_180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequest request) {
            return base.Channel.isAuthorized(request);
        }
        
        public bool isAuthorized(string userId, string password) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedResponse retVal = ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).isAuthorized(inValue);
            return retVal.Body.isAuthorizedReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedResponse> _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.isAuthorizedAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequest request) {
            return base.Channel.isAuthorizedAsync(request);
        }
        
        public System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedResponse> isAuthorizedAsync(string userId, string password) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isAuthorizedRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).isAuthorizedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoResponse _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.getUserInfo(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequest request) {
            return base.Channel.getUserInfo(request);
        }
        
        public string getUserInfo(string userId) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequestBody();
            inValue.Body.userId = userId;
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoResponse retVal = ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).getUserInfo(inValue);
            return retVal.Body.getUserInfoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoResponse> _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.getUserInfoAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequest request) {
            return base.Channel.getUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoResponse> getUserInfoAsync(string userId) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getUserInfoRequestBody();
            inValue.Body.userId = userId;
            return ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).getUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedResponse _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.isConnected(_180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequest request) {
            return base.Channel.isConnected(request);
        }
        
        public string isConnected() {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequestBody();
            _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedResponse retVal = ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).isConnected(inValue);
            return retVal.Body.isConnectedReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedResponse> _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.isConnectedAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequest request) {
            return base.Channel.isConnectedAsync(request);
        }
        
        public System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedResponse> isConnectedAsync() {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isConnectedRequestBody();
            return ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).isConnectedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoResponse _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.getTariffInfo(_180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequest request) {
            return base.Channel.getTariffInfo(request);
        }
        
        public string getTariffInfo(string userId) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequestBody();
            inValue.Body.userId = userId;
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoResponse retVal = ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).getTariffInfo(inValue);
            return retVal.Body.getTariffInfoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoResponse> _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.getTariffInfoAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequest request) {
            return base.Channel.getTariffInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoResponse> getTariffInfoAsync(string userId) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getTariffInfoRequestBody();
            inValue.Body.userId = userId;
            return ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).getTariffInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoResponse _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.getUsageInfo(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequest request) {
            return base.Channel.getUsageInfo(request);
        }
        
        public string getUsageInfo(string userId, string infoType) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.infoType = infoType;
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoResponse retVal = ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).getUsageInfo(inValue);
            return retVal.Body.getUsageInfoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoResponse> _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.getUsageInfoAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequest request) {
            return base.Channel.getUsageInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoResponse> getUsageInfoAsync(string userId, string infoType) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getUsageInfoRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.infoType = infoType;
            return ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).getUsageInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedResponse _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.isDBConnected(_180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequest request) {
            return base.Channel.isDBConnected(request);
        }
        
        public string isDBConnected() {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequestBody();
            _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedResponse retVal = ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).isDBConnected(inValue);
            return retVal.Body.isDBConnectedReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedResponse> _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.isDBConnectedAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequest request) {
            return base.Channel.isDBConnectedAsync(request);
        }
        
        public System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedResponse> isDBConnectedAsync() {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.isDBConnectedRequestBody();
            return ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).isDBConnectedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoResponse _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.getInvoiceInfo(_180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequest request) {
            return base.Channel.getInvoiceInfo(request);
        }
        
        public string getInvoiceInfo(string userId, int invoiceCount) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.invoiceCount = invoiceCount;
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoResponse retVal = ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).getInvoiceInfo(inValue);
            return retVal.Body.getInvoiceInfoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoResponse> _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.getInvoiceInfoAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequest request) {
            return base.Channel.getInvoiceInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoResponse> getInvoiceInfoAsync(string userId, int invoiceCount) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.getInvoiceInfoRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.invoiceCount = invoiceCount;
            return ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).getInvoiceInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordResponse _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.changeUserPassword(_180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequest request) {
            return base.Channel.changeUserPassword(request);
        }
        
        public bool changeUserPassword(string userId, string password) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordResponse retVal = ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).changeUserPassword(inValue);
            return retVal.Body.changeUserPasswordReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordResponse> _180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl.changeUserPasswordAsync(_180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequest request) {
            return base.Channel.changeUserPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<_180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordResponse> changeUserPasswordAsync(string userId, string password) {
            _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequest inValue = new _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequest();
            inValue.Body = new _180705_i2i_Cell2i.WebServiceReferenceV_2.changeUserPasswordRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((_180705_i2i_Cell2i.WebServiceReferenceV_2.Cell2iWebServiceImpl)(this)).changeUserPasswordAsync(inValue);
        }
    }
}
